
workflows:
  ios-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - brayden.eberle@hotmail.com
